### ISSUE TITLE
Question: IS this repo different? A lotta variations! <3

### ISSUE THREAD

**Issue by BrandonKMLee** [dmuth/diceware#19]
- [ ] https://github.com/mandulaj/diceware-v6/blob/master/diceware-v6.txt.asc
- [ ] https://github.com/nightsense/eyeware/blob/master/eyeware-wordlist
- [ ] https://github.com/nightsense/eyeware/blob/master/eyeware8k
- [ ] https://github.com/emilbayes/eff-diceware-passphrase/blob/master/eff_large_wordlist.txt
- [ ] https://github.com/emilbayes/eff-diceware-passphrase/blob/master/wordlist.json
- [ ] https://github.com/kalpetros/hawkpass/tree/master/src/wordlists
- [ ] https://github.com/ulif/diceware/tree/master/diceware/wordlists
- [ ] https://github.com/micahflee/passphraseme/tree/master/passphraseme/wordlists
- [ ] https://github.com/thoughtworks/dadoware/blob/master/7776palavras-2e.txt
- [ ] https://github.com/thoughtworks/dadoware/blob/master/7776palavras-numeradas-2e.txt
- [ ] https://github.com/thoughtworks/dadoware/blob/master/7776palavras-numeradas.txt
- [ ] https://github.com/thoughtworks/dadoware/blob/master/7776palavras.txt
- [ ] https://github.com/thoughtworks/dadoware/blob/master/dadoware.txt
- [ ] https://github.com/sethvargo/go-diceware/tree/main/diceware
- [ ] https://github.com/heartsucker/diceware/tree/develop/wordlists/en_US
- [ ] https://github.com/cfbao/chinese-diceware/blob/master/pinyin.wordlist
- [ ] https://github.com/cfbao/chinese-diceware/blob/master/pinyin8k.wordlist
- [ ] https://github.com/cfbao/chinese-diceware/blob/master/wubi.wordlist
- [ ] https://github.com/cfbao/chinese-diceware/blob/master/wubi8k.wordlist
- [ ] https://github.com/mbelivo/diceware-wordlists-fr/blob/master/wordlist_fr_4d.txt
- [ ] https://github.com/mbelivo/diceware-wordlists-fr/blob/master/wordlist_fr_4d_2.txt
- [ ] https://github.com/mbelivo/diceware-wordlists-fr/blob/master/wordlist_fr_4k.txt
- [ ] https://github.com/mbelivo/diceware-wordlists-fr/blob/master/wordlist_fr_5d.txt
- [ ] https://github.com/ctsrc/Pgen/blob/master/eff_large_wordlist.txt
- [ ] https://github.com/ctsrc/Pgen/blob/master/eff_short_wordlist_1.txt
- [ ] https://github.com/ctsrc/Pgen/blob/master/eff_short_wordlist_2_0.txt
- [ ] https://github.com/canerbasaran/diceware_tr/blob/master/diceware_tr.txt
- [ ] https://github.com/mgumz/diceware
- [ ] https://github.com/1ma/diceware-cat/blob/master/cat-wordlist-ascii.txt
- [ ] https://github.com/1ma/diceware-cat/blob/master/cat-wordlist-utf8.txt
- [ ] https://github.com/esumbar/passphrase/tree/master/database/raw_data
- [ ] https://github.com/luczsoma/HungarianDiceware/blob/master/hungarian-diceware.txt
- [ ] https://github.com/luczsoma/HungarianDiceware/blob/master/hungarian-diceware.json
- [ ] https://github.com/yesiamben/diceware/tree/master/js/lists
- [ ] https://github.com/biddster/diceware/tree/develop/src/main/resources
- [ ] https://github.com/eclarke/diceware/blob/master/word.list
- [ ] https://github.com/bdewey/Diceware-for-iOS/tree/master/Passphrase
- [ ] https://github.com/bdewey/Diceware-for-iOS/blob/master/diceware.wordlist.txt
- [ ] https://github.com/sahil-rajput/Diceware-Password-Generator/blob/master/Word%20List/wordlist.txt
- [ ] https://github.com/shamrin/diceware/blob/master/words
- [ ] https://github.com/jatenate/diceware/blob/master/lib/diceware.wordlist.txt
- [ ] https://github.com/iamcryptoki/passcat-go/tree/master/passcat
- [ ] https://github.com/DeepLab/deeplab-x-diceware/blob/master/diceware.wordlist.asc.txt
- [ ] https://github.com/ct-clearhaus/diceware-danish/blob/master/diceware.wordlist-danish.txt
- [ ] https://github.com/pedromanoel/diceware-ptbr/blob/master/dicionario-pt.txt
- [ ] https://github.com/fmichonneau/riceware/tree/master/inst/extdata
- [ ] https://github.com/trenc/roll_password/blob/master/diceware_wordlist_en
- [ ] https://github.com/trenc/roll_password/blob/master/diceware_wordlist_de
- [ ] https://github.com/jtomori/diceware_slovak/blob/master/diceware_sk_5_rolls
- [ ] https://github.com/jtomori/diceware_slovak/blob/master/diceware_sk_6_rolls
- [ ] https://github.com/jtomori/diceware_slovak/blob/master/diceware_sk_7_rolls
- [ ] https://github.com/patarapolw/diceware_utils/tree/master/diceware_utils/database/wordlist
- [ ] https://github.com/raspberryaether/dwpwg/blob/master/dwpwg/lists/en/full
- [ ] https://github.com/Taipo/MaoriDiceware/blob/master/diceware_maori.txt
- [ ] https://github.com/Aaron-P/KeeDiceware/tree/master/KeeDiceware/Wordlists
- [ ] https://github.com/Freaky/mkpass/tree/master/dictionaries
- [ ] https://github.com/arothstein/goodpassphrase/blob/master/public/words.js
- [ ] https://github.com/guzart/rassphrase/tree/master/lib
- [ ] https://github.com/ntmoe/diceware

**Comment by BrandonKMLee** [comment]
Also
- https://ae7.st/g/
- https://theworld.com/~reinhold/diceware.html
- https://github.com/stuarta0/ultimate-diceware/tree/master/source

Press F to https://github.com/grempe/diceware/issues/50

**Comment by BrandonKMLee** [comment]
- [ ]  https://github.com/stephenwashington/diceware/tree/master/data
- [ ] https://github.com/dougsko/diceware/tree/master/data
- [ ] https://github.com/sylviamoss/diceware-cli/tree/master/words
- [ ] https://github.com/Richard-Payne/DiceWarePasswordGenerator/tree/master/DicewareLib/WordLists
- [ ] https://github.com/oconnore/diceware/blob/master/diceware.txt
- [ ] https://github.com/oconnore/diceware/blob/master/combo.txt
- [ ] https://github.com/tsuchm/diceware-ja/blob/master/wordlist.csv
- [ ] https://github.com/KayJay7/my_diceware/blob/main/assets/diceware.wordlist.asc
- [ ] https://github.com/brsmsn/gware/tree/master/test/worldlists
- [ ] https://github.com/jamiehale/diceware.rb/blob/master/wordlist-final.txt
- [ ] https://github.com/oconnore/diceware/blob/master/beale.txt
- [ ] https://github.com/toffer/pydiceware/tree/master/diceware/data
- [ ] https://github.com/DanielSkube/Disco-For-Diceware/tree/master/wordLists
- [ ] https://github.com/azophy/frasa-sandi/blob/master/wordlist/kompas.lst
- [ ] https://github.com/BTBTravis/byod-diceware-helper/blob/master/public/dicedata.js
- [ ] https://github.com/esmorga/pyce/blob/master/wordlist.txt
- [ ] https://github.com/shawnfuryan/diceware_prng/blob/master/wordlist.csv
- [ ] https://github.com/krislamo/Dicekey/blob/master/dicekey/wordlist.asc
- [ ] https://github.com/tarcisio-marinho/bitbox/tree/master/wordlists
- [ ] https://github.com/ckxng/diceware-web/blob/master/public/js/eff.js
- [ ] https://github.com/ycao15/Diceware/blob/master/dictionary.txt

**Comment by dmuth** [comment]
Hi,

I'm not sure what kind of answer you were looking for, but I can tell you that I built this implementation from scratch, except for the wordlist, which comes from the EFF: https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases

-- Doug
