### ISSUE TITLE
website breaks if you spam click on generate password 

### ISSUE THREAD

**Issue by KripC2160** [dmuth/diceware#24]
![Screenshot 2021-05-15 171018](https://user-images.githubusercontent.com/65854891/118353268-7955e800-b5a0-11eb-8c97-c1fca44a1db5.png)

you should disable the buttons while the password is being generated in order to prevent this from happening. Not only it generates a lot of text, it also prevents you from doing anything on website (frozen) and only way is to reload or close off and come back

**Comment by dmuth** [comment]
Yep, that's a bug alright!  Nice find.

I'll take a whack at it.

**Comment by dmuth** [comment]
Documenting here--I get some absolutely _wild_ errors on the Javascript console as well.  OP wasn't kidding!

![image](https://user-images.githubusercontent.com/374060/118375615-bf0ab480-b590-11eb-91e2-43188fbc9fc7.png)

**Comment by dmuth** [comment]
Okay, I made, tested, and deployed the fix!  If you go to https://diceware.dmuth.org/?debug=4 and start mashing the button, you should see it working correctly now.

Note that the website is served via CloudFront, so it _may_ take up to 24 hours for changes to propagate worldwide--if you don't see the changes after that, please let me know.

I'm gonna mark this as closed, but leave it open for commenting.

Thanks for bringing this to my attention.

-- Doug

**Comment by KripC2160** [comment]
I just tested it once again and it's working perfectly!
