### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by OfficialAudite** [dmuth/diceware#35]
What license is it under? 
Can I modify it ? 
I will definitely credit you for your hard work but I would love to change the design, remove some of the text and stuff like that.

**Comment by dmuth** [comment]
> What license is it under?

It's under the GPL: https://github.com/dmuth/diceware/blob/main/LICENSE

I maaaay change that to Apache, especially if there's a need for it.

> Can I modify it ?

Sure!  Just do so in according with the license (and I may change it to Apache if that suits your use case better)

Thanks!

-- Doug

**Comment by OfficialAudite** [comment]
Lovely! GPL works fantastic 👍🏻 
Thanks for quick answer :P 
The domain that I'm using is https://safepass.nu
