### ISSUE TITLE
Should probably not recommend LastPass by name

### ISSUE THREAD

**Issue by shodgson11** [dmuth/diceware#36]
At this point, your website (e.g. https://diceware.dmuth.org/?debug=4&skip_animation) should probably not recommend LastPass by name.  They've chosen to hide behind PR-speak instead of being forthright about their current situation (e.g. https://palant.info/2022/12/26/whats-in-a-pr-statement-lastpass-breach-explained/).

**Comment by dmuth** [comment]
Thanks for sharing, that was a very thorough read that helps put things into perspective.  I'll update this shortly.
