### ISSUE TITLE
address space for 6 and 7

### ISSUE THREAD

**Issue by testingroger** [dmuth/diceware#37]
when a 6 dice are selected, it says # of possible passwords:
221,073,919,720,733,360,000,000  that indicates a word list of 7776 i believe.  

But in the FAQ it states:
 FAQ: Can you tell me more about the list of words? "Peter Norvig's (1/3 million) list is still in use for when 6 or 7 dice are rolled."

FAQ: How many dice are rolled per word?
"you can run Diceware with [6 dice per word](https://diceware.dmuth.org/?dice=6) and [7 dice per word](https://diceware.dmuth.org/?dice=7) (for 46,655 and 279,935 possible words, respectively),"

update faq to indicate the word list used by 6 and 7 as necessary to make it clear its using the 7776 word list.

thanks for an awesome project.

**Comment by dmuth** [comment]
Thanks for catching that--that sentence was a leftover from a past implementation, so I removed it.
