### ISSUE TITLE
Modulo reduction introduces bias

### ISSUE THREAD

**Issue by paragonie-security** [dmuth/diceware#7]
https://github.com/dmuth/diceware/blob/336c7cd37505b5537d6a721a6b72c364b14eac4e/main.js#L40

This is sort of a common CSPRNG anti-pattern where byte strings are converted to integers. To prove the bias, consider the following mapping:

```js
function demonstrateBias(max) {
  if (typeof max !== 'number') {
    throw("Invalid type");
  }
  var map = new Array(max);
  // Initialize the values at 0
  for (var i = 0; i < max; i++) {
    map[i] = 0;
  }

  for (var i = 0; i < 256; i++) {
    map[i % max]++;
  }
  return map;
}
```

And then if you run this:

```
demonstrateBias(3);
[86, 85, 85]
demonstrateBias(6);
[43, 43, 43, 43, 42, 42]
```

So what ends up happening is you get some values slightly more often, even given a secure random source, which can be used by attackers to have a higher probability of guessing your generated passphrase.

The solution implemented [here](https://github.com/joepie91/node-random-number-csprng/blob/master/lib/index.js#L49-L144) has been reviewed by cryptographers and Node.js security experts and is available under WTFPL / CC0 if you'd like to adapt this library (or use it as a module).

**Comment by paragonie-security** [comment]
Note: If `max` is an even power of 2 (2, 4, 8, 16, 32, 64, 128, 256, ...) then the bias is nonexistent, because there are an equal number of outputs for every possible input.

**Comment by dmuth** [comment]
Ohhhh... that's not so good.

Thank for you catching that.  I've never actually dealt with this kind of bug before, so let me dig into this and get a fix out.

--- Doug

**Comment by dmuth** [comment]
Well, this was a fun evening.  Ended up having to convert a bunch of my code over to use Promises and in the process discovered that QUnit doesn't play nice with webpack.  Good times!

I've got the fix sitting in a branch, which I'll deploy when I get home from work tomorrow evening.

And I filed #8 to redo the unit tests in Mocha.

And now, I sleep: 

![image](https://user-images.githubusercontent.com/374060/32588556-7c7dd572-c4dd-11e7-9e7a-95e650a6cae0.png)

-- Doug

**Comment by dmuth** [comment]
Okay, this has been fixed and deployed:

```
$ curl -s https://www.dmuth.org/diceware/main.js |grep "% max" |wc -l
       0
$ curl -s https://www.dmuth.org/diceware/dist/bundle.js |grep "% max" |wc -l
       0
```

This is definitely a better way to get random numbers, and my only regret is that including this library and all dependencies bloated the Javascript from 14 K to 810 K, which is really gonna impact people on cellular networks.

I'm gonna close this one out, but if I screwed anything up, don't hesitate to comment here or open a new bug against me. 

-- Doug
